version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
  groups:
    dependencies:
      patterns:
      - "*"
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
  groups:
    dependencies:
      patterns:
      - "*"
  open-pull-requests-limit: 10
