require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-graphql
  - rubocop-factory_bot


AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  Exclude:
    - db/schema.rb
    - vendor/**/*
    - tmp/**/*
    - bin/**/*
    - db/seeds/**/*

RSpec:
  Language:
    Helpers:
      - let_blueprint
      - let_blueprint_build
      - let_blueprint_create
      - letbp
      - let_blueprint!
      - let_blueprint_build!
      - let_blueprint_create!
      - letbp!

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/Documentation:
  Enabled: false

# Use the Rails default style
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

# Prefer shorter syntax for hashes
Style/HashSyntax:
  Enabled: true
  EnforcedStyle: ruby19_no_mixed_keys
  EnforcedShorthandSyntax: always

# Prefer consistent comma usage
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

# Allow numbered parameters usage like `reduce { _1 + _2 }`
Style/NumberedParametersLimit:
  Max: 2

RSpec/NamedSubject:
  EnforcedStyle: named_only

# Prefer code readability over order strictness
GraphQL/OrderedArguments:
  Enabled: false
GraphQL/OrderedFields:
  Enabled: false

# Disable object description requirement to simplify this example
GraphQL/ArgumentDescription:
  Enabled: false
GraphQL/ObjectDescription:
  Enabled: false
GraphQL/FieldDescription:
  Enabled: false

# Disable some annoying cops
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false

# Prefer explicit FactoryBot associations like `association :user`
FactoryBot/AssociationStyle:
  EnforcedStyle: explicit
